<a href="https://colab.research.google.com/github/gaurika05/Neural_Networks_Deep_Learning/blob/main/ANN_FROM_SCRATCH(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
x = np.array([
    [1,0,1,0],
    [1,0,1,1],
    [0,1,0,1]
])

y = np.array([[1],[1],[0]])

In [ ]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [ ]:
x.shape

(3, 4)

In [ ]:
inputNeurons = x.shape[1]
hiddenNeurons = 4
outputNeurons = 1

In [ ]:
#Draw samples from a uniform distribution.
weightsHidden = np.random.uniform(size=(inputNeurons,hiddenNeurons))
biasHidden = np.random.uniform(size=(1,hiddenNeurons))
weightsOutput = np.random.uniform(size=(hiddenNeurons,outputNeurons))
biasOutput = np.random.uniform(size=(1,outputNeurons))

In [ ]:
fx = np.dot(x,weightsHidden) + biasHidden

In [ ]:
hiddenLayer = sigmoid(fx)

In [ ]:
hiddenLayer

array([[0.78652315, 0.87828038, 0.64984742, 0.88976933],
       [0.89695684, 0.91134467, 0.66785892, 0.94372169],
       [0.76205596, 0.7796693 , 0.72140882, 0.90692532]])

In [ ]:
f_x = np.dot(hiddenLayer,weightsOutput) +biasOutput

In [ ]:
f_x

array([[2.03793024],
       [2.11042275],
       [2.00644233]])

In [ ]:
biasHidden

array([[0.29311255, 0.40257024, 0.27859214, 0.79686909]])

In [ ]:
biasOutput

array([[0.3804592]])

In [ ]:
outputLayer = sigmoid(f_x)

In [ ]:
outputLayer

array([[0.88472234],
       [0.8919121 ],
       [0.88147182]])

In [ ]:
#Backpropagation

In [ ]:
def derivativeSigmoid(x):
  return x * (1 - x)

In [ ]:
errorOutput = outputLayer - y
slopeOutput = derivativeSigmoid(outputLayer)
deltaOutput = errorOutput * slopeOutput

In [ ]:
errorOutput.shape

(3, 1)

In [ ]:
deltaOutput.shape

(3, 1)

In [ ]:
weightsOutput.shape

(4, 1)

In [ ]:
errorHidden = np.dot(deltaOutput,weightsOutput.T)
slopeHidden = derivativeSigmoid(hiddenLayer)
deltaHidden = errorHidden * slopeHidden

In [ ]:
#code starts here....(lecture 4)

In [ ]:
errorOutput

array([[-0.11527766],
       [-0.1080879 ],
       [ 0.88147182]])

In [ ]:
alpha =0.01
weightsOutput = weightsOutput - hiddenLayer.T.dot(deltaOutput) * alpha
weightsHidden = weightsHidden - x.T.dot(deltaHidden) * alpha
biasOutput = biasOutput - np.sum(deltaOutput) * alpha
biasHidden = biasHidden - np.sum(deltaHidden) * alpha

In [ ]:
weightsHidden = np.random.uniform(size=(inputNeurons,hiddenNeurons))
biasHidden = np.random.uniform(size=(1,hiddenNeurons))
weightsOutput = np.random.uniform(size=(hiddenNeurons,outputNeurons))
biasOutput = np.random.uniform(size=(1,outputNeurons))

In [ ]:
#Combined code here

In [ ]:
# Train together(for optimization run the code again and again)
#alpha and epochs value changed to optimize
alpha = 0.01
epochs = 30000

for i in range(epochs):
  #Feedforward
  #Step-1->apply dot product and add bias
  fx = np.dot(x,weightsHidden) + biasHidden
  #Step-2->apply activation function
  hiddenLayer = sigmoid(fx)
  #Step-3->apply dot product and add  bias
  f_x = np.dot(hiddenLayer,weightsOutput) +biasOutput
  #Step-4->apply activation function on output layer
  outputLayer = sigmoid(f_x)

  #Backpropagation
  #Error on output layer
  errorOutput = outputLayer - y
  #slope on iutput layer -
  slopeOutput = derivativeSigmoid(outputLayer)
  #delta = error x slope
  deltaOutput = errorOutput * slopeOutput
  errorHidden = np.dot(deltaOutput,weightsOutput.T)
  slopeHidden = derivativeSigmoid(hiddenLayer)
  deltaHidden = errorHidden * slopeHidden

  weightsOutput = weightsOutput - hiddenLayer.T.dot(deltaOutput) * alpha
  weightsHidden = weightsHidden - x.T.dot(deltaHidden) * alpha
  biasOutput = biasOutput - np.sum(deltaOutput) * alpha
  biasHidden = biasHidden - np.sum(deltaHidden) * alpha

In [ ]:
outputLayer

array([[0.97562312],
       [0.96554095],
       [0.04547918]])