<a href="https://colab.research.google.com/github/gaurika05/Neural_Networks_Deep_Learning/blob/main/feedforward(ANN)_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

feedforward (without pytorch)

In [ ]:
import numpy as np

In [ ]:
x=np.array([
    [1,0,1,0],
    [1,0,1,1],
    [0,1,0,1]
    ])

y=np.array([[1],[1],[0]])

In [ ]:
#Activation function
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [ ]:
x.shape

(3, 4)

In [ ]:
#input layer neurons will always be able equal to the number of columns
inputNeurons = x.shape[1]
#hidden neurons we can decide by hit and trial
hiddenNeurons = 3
#output neurons depends on number of classes we have in target column
outputNeurons = 1

In [ ]:
weightsHidden = np.random.uniform(size=(inputNeurons , hiddenNeurons))
biasHidden = np.random.uniform(size=(1,hiddenNeurons))
weightsOutput = np.random.uniform(size=(hiddenNeurons, outputNeurons))
biasOutput = np.random.uniform(size=(1,outputNeurons))

In [ ]:
#Feedforward
#Step-1 - apply dot product and add bias : f(x) = x.wh +biasHidden
fx= np.dot(x,weightsHidden) + biasHidden

In [ ]:
#Step -2 -apply activation function
hiddenLayer = sigmoid(fx)

In [ ]:
hiddenLayer

array([[0.68349469, 0.83388217, 0.70804354],
       [0.84323571, 0.92528736, 0.71269911],
       [0.78576854, 0.84317475, 0.76143731]])

In [ ]:
#Step -3 - apply dot product and bias : f(x)= hiddenLayer.wout + biasOut
fx_ = np.dot(hiddenLayer, weightsOutput) + biasOutput

In [ ]:
fx_

array([[1.33878512],
       [1.46774171],
       [1.43718464]])

In [ ]:
biasHidden

array([[0.12485594, 0.55769099, 0.14871212]])

In [ ]:
biasOutput

array([[0.20474312]])

In [ ]:
outputLayer = sigmoid(fx_)

In [ ]:
outputLayer

array([[0.79229008],
       [0.81271389],
       [0.8080183 ]])

backpropagation

In [ ]:
def derivativeSigmoid(x):
  return x *(1-x)

In [ ]:
#Backpropagation

#Error on output layer
errorOutput = outputLayer - y
# Slope on output layer - derivative of activation function applied on this layer
slopeOutput = derivativeSigmoid(outputLayer)
#Delta =error x slope
deltaOutput = errorOutput * slopeOutput

In [ ]:
errorHidden = np.dot(deltaOutput,weightsOutput.T)  # very important step
slopeHidden = derivativeSigmoid(hiddenLayer)
deltaHidden = errorHidden * slopeHidden

In [ ]:
#deltaOutput.shape
#weightsOutput.shape
#slopeHidden.shape
#deltaHidden.shape

(3, 3)