<a href="https://colab.research.google.com/github/gaurika05/Neural_Networks_Deep_Learning/blob/main/pytorch_intro(3).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import torch

In [ ]:
# Here double underscore is used
torch.__version__

'2.0.1+cu118'

In [ ]:
x = np.array([[1,2,4],[6,4,8],[6,6,8],[7,9,2]])

In [ ]:
x.shape

(4, 3)

In [ ]:
type(x)

numpy.ndarray

In [ ]:
data=[[1,2,4],[6,4,8],[6,6,8],[7,9,2]]
x_tensor = torch.tensor(data)

In [ ]:
x_tensor

tensor([[1, 2, 4],
        [6, 4, 8],
        [6, 6, 8],
        [7, 9, 2]])

In [ ]:
x_tensor.size()

torch.Size([4, 3])

In [ ]:
scalar = torch.tensor(5)
#torch.tensor.item() does not take 2d tensor as an argument

In [ ]:
scalar

tensor(5)

In [ ]:
#to know the scalar single quantity inside the bracket
scalar.item()

5

In [ ]:
#for 1d array
vector = torch.tensor([5,9])

In [ ]:
vector

tensor([5, 9])

In [ ]:
vector.shape

torch.Size([2])

 scalar - single array,
 vector - 1D array,
 matrix - 2D array,
 tensor - Nd array

In [ ]:
torch.zeros((4,5))

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [ ]:
torch.zeros(0)

tensor([])

In [ ]:
torch.zeros([4])

tensor([0., 0., 0., 0.])

In [ ]:
torch.ones(5)

tensor([1., 1., 1., 1., 1.])

In [ ]:
torch.ones((4,4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
torch.rand(6)

tensor([0.0399, 0.2593, 0.9646, 0.8532, 0.2536, 0.6281])

In [ ]:
x = torch.rand((4,6))#values between 0 and 1 (4 rows and 6 columns)

In [ ]:
x.shape

torch.Size([4, 6])

In [ ]:
x.dtype

torch.float32

In [ ]:
x.device

device(type='cpu')

In [ ]:
tensor = torch.tensor([4,3,4])

In [ ]:
tensor

tensor([4, 3, 4])

In [ ]:
tensor + 5   #??????? add

tensor([9, 8, 9])

In [ ]:
tensor * 2 #multiply

tensor([8, 6, 8])

In [ ]:
[3,5,7] * 2  #repetition

[3, 5, 7, 3, 5, 7]

In [ ]:
tensor_2 = torch.tensor([1,2,3])

In [ ]:
tensor + tensor_2

tensor([5, 5, 7])

In [ ]:
tensor * tensor_2

tensor([ 4,  6, 12])

In [ ]:
x = torch.tensor([
    [1,2,3,4],
    [2,3,4,5],
    [5,6,7,8]
])

y = torch.tensor([
    [9,12,11,10],
    [1,2,3,2],
    [5,6,7,8]
])

In [ ]:
x + y

tensor([[10, 14, 14, 14],
        [ 3,  5,  7,  7],
        [10, 12, 14, 16]])

In [ ]:
x*y

tensor([[ 9, 24, 33, 40],
        [ 2,  6, 12, 10],
        [25, 36, 49, 64]])

In [ ]:
%%time
torch.matmul(x,y.T)

CPU times: user 82 µs, sys: 15 µs, total: 97 µs
Wall time: 101 µs


tensor([[106,  22,  70],
        [148,  30,  96],
        [274,  54, 174]])

In [ ]:
# either use matmul or @ or mm

In [ ]:
x @ y.T

tensor([[106,  22,  70],
        [148,  30,  96],
        [274,  54, 174]])

In [ ]:
torch.mm(x,y.T)

tensor([[106,  22,  70],
        [148,  30,  96],
        [274,  54, 174]])

In [ ]:
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.linspace(1,100,20) #linear space array genrate 20 elements

tensor([  1.0000,   6.2105,  11.4211,  16.6316,  21.8421,  27.0526,  32.2632,
         37.4737,  42.6842,  47.8947,  53.1053,  58.3158,  63.5263,  68.7368,
         73.9474,  79.1579,  84.3684,  89.5789,  94.7895, 100.0000])

In [ ]:
x = torch.randint(1,10,(1,2))

tensor([[2, 1]])

In [ ]:
torch.randint(1,10,size=(3,4))

tensor([[2, 6, 9, 9],
        [7, 3, 1, 9],
        [6, 4, 9, 9]])

In [ ]:
x.sum()

tensor(71)

In [ ]:
x.type(torch.float32).mean()

tensor(5.9167)

In [ ]:
x = torch.randint(1,50,size=(24,))

In [ ]:
x.shape

torch.Size([24])

In [ ]:
x

tensor([32, 45, 10, 44,  1, 11, 32, 48, 27, 20,  3, 42, 22, 42, 49,  7, 34, 44,
        40, 36, 23, 13, 44, 14])

In [ ]:
x = x.reshape(4,6)

In [ ]:
x.view(6,4)

tensor([[32, 45, 10, 44],
        [ 1, 11, 32, 48],
        [27, 20,  3, 42],
        [22, 42, 49,  7],
        [34, 44, 40, 36],
        [23, 13, 44, 14]])

In [ ]:
x[0]

tensor([32, 45, 10, 44,  1, 11])

In [ ]:
x[:,0]

tensor([32, 32, 22, 40])

In [ ]:
x[0:3,0:2]

tensor([[32, 45],
        [32, 48],
        [22, 42]])